name       : parole
version    : 4.18.0
release    : 1
source     :
    - https://archive.xfce.org/src/apps/parole/4.18/parole-4.18.0.tar.bz2 : bbe52fbc4d3abe30f6c79fc7ac57bd9de9cf74ce1a79b508a1d7de83dc4f3771
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : Modern media player based on the GStreamer framework.
description: |
    Modern media player based on the GStreamer framework.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(libnotify)
    - pkgconfig(libxfce4ui-2)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
